version: "3"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: npm run start-watch
    volumes: 
      - ./api:/usr/app/
      - ./api/node_modules:/usr/app/node_modules
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      MONGO_URL: mongodb://192.81.212.107:27017/${MONGO_INITDB_DATABASE}
      MONGO_USER: ${MONGO_USERNAME}
      MONGO_PWD: ${MONGO_PASSWORD}
      IS_LOCAL: ${IS_LOCAL}
  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile-staging
    command: npm run start --public
    volumes:
      - ./webapp:/usr/app/
      - ./webapp/node_modules:/usr/app/node_modules
    ports:
      - "80:8080"
    depends_on:
      - api
    environment:
      NODE_ENV: development